import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Page owned by{' '}
          <code className={styles.code}>anantab</code>
        </p>

        <div className={styles.grid}>
          <Link href="/chess" className={styles.card}>
            <h2>Chess &rarr;</h2>
            <p>Check a basic chess game built with <code>js-chess-engine</code></p>
          </Link>

          <a
            href="https://anntz.com"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Portfolio &rarr;</h2>
            <p>
              A basic portfolio site built with plain HTML && tailwind.css 
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
